services:
  nginx:
    image: nginx:1.26.2-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/src
    ports:
      - 80:80
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: 1000:1000
    volumes:
      - ./src:/src
    working_dir: /src
    depends_on:
      - db
  db:
    image: mysql:8.1
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=reservations-backpack
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 81:80
    environment:
      - MYSQL_ROOT_PASSWORD=root
